spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:warehouse
    username: warehouse
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
